# Generated by Django 3.0.8 on 2020-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('movie_poster', models.ImageField(upload_to=None)),
                ('movie_description', models.TextField(null=True)),
                ('movie_created_date', models.DateField()),
                ('movie_release_date', models.DateField()),
            ],
        ),
    ]
