# Generated by Django 3.0.8 on 2020-07-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_data',
            name='movie_poster',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
